# Generated by Django 3.2.6 on 2021-09-06 16:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('backgroud_image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('Homeserviceimages2', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('Homeserviceimages3', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('Heading', models.CharField(max_length=500)),
                ('more_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
