# Generated by Django 3.2.7 on 2021-09-08 19:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Long_description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Client Reviews',
                'verbose_name_plural': 'Client Reviews',
            },
        ),
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('float_icon', models.CharField(max_length=250)),
                ('counter', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Counter +',
                'verbose_name_plural': 'Counter +',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Logoimage', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('sliderimage', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=500)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='service_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('Homeserviceimage', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('Short_description', models.CharField(max_length=500)),
                ('Long_description', tinymce.models.HTMLField()),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_service', to='service.service')),
            ],
            options={
                'verbose_name': 'Home service',
                'verbose_name_plural': 'Home service',
            },
        ),
    ]
