# Generated by Django 3.2.7 on 2021-09-14 18:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('about_image_3', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('about_image_4', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('Short_description', models.CharField(max_length=500)),
                ('Long_description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
