# Generated by Django 3.2.7 on 2021-09-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_page',
            old_name='about_image_1',
            new_name='background_banner_img',
        ),
    ]
