# Generated by Django 3.2.7 on 2021-09-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210916_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_page',
            old_name='about_image_2',
            new_name='about_image',
        ),
        migrations.RemoveField(
            model_name='about_page',
            name='about_image_3',
        ),
        migrations.RemoveField(
            model_name='about_page',
            name='about_image_4',
        ),
        migrations.AlterField(
            model_name='about_page',
            name='background_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
