# Generated by Django 3.2.6 on 2021-09-06 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watch_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(null=True, upload_to='images_uploaded')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'video Lactures',
                'verbose_name_plural': 'videos Lactures',
            },
        ),
    ]
